### ISSUE TITLE
想请问下oneil_drug_informax_feat.txt中包含的信息是？

### ISSUE THREAD

**Issue by hhhwy** [yushenshashen/MGAE-DC#1]
想请问下代码里面用oneil_drug_informax_feat.txt做为药物的初始特征，这个信息是包含了哪些信息呢？是如何计算得到的呢？期待回复！

**Comment by zhangpengxx** [comment]
Zagidullin et al在下面的文章中系统比较了通过七种常见的药物分子指纹预测药物组合的效果，发现通过Informax模型获得的模型表现最好。因此，我们在本文中使用药物的Informax分子指纹作为药物的特征。祝好运！
Zagidullin et al. Comparative analysis of molecular fingerprints in prediction of drug combination effects. BIB. 2021

**Comment by hhhwy** [comment]
好的，非常感谢！
